- name: ensure git is installed
  apt: pkg=git    
- name: ensure easy_install is installed
  apt: pkg=python-setuptools    
- name: ensure Pygments is installed
  easy_install: name=Pygments 
- name: ensure nodejs is installed 
  apt: pkg=nodejs 
- name: ensure grunt-cli is installed 
  npm: name=grunt-cli global=yes
- name: ensure bower is installed 
  npm: name=bower global=yes
- include: phantomjs.yml
